#!/bin/bash

echo -n "Username: "
read username

echo -n "Password: "
read -s password

echo ""

echo -n "Retype password: "
read -s retypepassword

echo ""

[[ "$password" == "$retypepassword" ]] && {
        echo "$username:$password"|chpasswd --crypt-method SHA512
        exit 0
} || {
        echo "Password did not match, try again"
        exit 1
}
